/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Modal} from 'react-native';
import {ShadowView, CommonPicker} from '@byron-react-native/design';

const typeList = ['色情暴力', '违法内容', '广告骚扰', '侮辱谩骂', '其他'];

export default class App extends Component {
  state = {
    visible: false,
    type: '广告骚扰',
  };

  onCloseModal = () => {
    this.setState({visible: false});
  };
  onPickerConfirm = vals => {
    const val = vals[0] || '';
    this.setState({type: val});
    this.onCloseModal();
  };

  render() {
    return (
      <View style={styles.container}>
        <ShadowView style={styles.shadow}>
          <Text
            style={styles.welcome}
            onPress={() => this.setState({visible: true})}>
            ☆RNByronDesign example☆
          </Text>
          <Text style={styles.instructions}>STATUS: loaded</Text>
          <Text style={styles.welcome}>☆☆☆</Text>
        </ShadowView>
        <Modal visible={this.state.visible} statusBarTranslucent={true}>
          <View style={{flex: 1, backgroundColor: 'rgba(0,0,0,0.3)'}} />
          <CommonPicker
            pickerData={typeList}
            selectedValue={[this.state.type]}
            onPickerCancel={this.onCloseModal}
            onPickerConfirm={this.onPickerConfirm}
          />
        </Modal>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  shadow: {
    height: 200,
    width: 300,
    marginVertical: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    backgroundColor: '#fff',
    borderRadius: 12,
  },
});
